version: '2'

services:
  proxy:
    image: nginx:latest
    container_name: "nginx"
    ports:
        - "8080:80"
    networks:
      - local

  php:
    image: php:7-fpm
    container_name: "php7"
    networks:
      - local

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8080:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${MYSQL_HOST}
    restart: always

networks:
  local:
    driver: bridge
